### ISSUE TITLE
SINTESIS 

### ISSUE THREAD

**Issue by CxrlosMX** [SistemasTecTlaxiaco/actividad-3-sintesis-CxrlosMX#2]
[Sintesis - Gestión de proyectos de software.pdf](https://github.com/SistemasTecTlaxiaco/actividad-3-sintesis-CxrlosMX/files/9484040/Sintesis.-.Gestion.de.proyectos.de.software.pdf)

**Comment by Yabin-2021** [comment]
20%

**Comment by josealfredo79** [comment]
@Yabin-2021 debes evaluar correctamente el trabajo

**Comment by josealfredo79** [comment]
BIen hechos y revisado..
